[project]
name = "ArithmeticAgent"
version = "0.1.0"
description = "A chatbot with  agent having  Arithmetic capabilities"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.27",
    "langchain-groq>=0.3.8",
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.1",
]
